language: node_js
node_js: stable
dist: trusty
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn run lint
  - xvfb-run yarn run test:sauce
  - yarn run test
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - yarn run report-coverage
  - yarn run semantic-release
notifications:
  email: change
