language: node_js
node_js: stable
dist: trusty
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn run test:sauce
  - yarn run test
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - yarn run report-coverage
  - yarn run semantic-release
notifications:
  email: change
addons:
  jwt:
    secure: KBfNGJ4iD2bwqe9xmH84lIm54PWzd8meNXnaanJvhzVtbnAdKCXQiLYMw0OzG2OsfRJqs4faYPEF8Ovto4q3VDnZ8LBhp4iICWZhuJkEVBUbZxjs3xzo9TwX9DSuq39kL9hM79lc14DeoD4rMq+iSFndfD3OvUPp5DNfX/3EOZSTLuFcpvuT6JPejQKcpq6xlQMAoMYC8PQGICiLdqio2qKZzY76/WEjfllFl4U3/M8Gkdyc/3oPXpAl2TB2Snp4Zmr7spXWpJZLFU61RQ+DCPoO6wEQMJbO9ysH5lIYr8R3ARYsjCZ3Ewk41X4vFwvkvYkv5MqryGVc5REbA2Zwx2SemLH7zvJfDVKIYyVLppkUWNvztkqdzOqgPBa41hT2IlvThhiRlfvriFipksKsxPgxwi4eeOGNh9BW8F/V25sn5VPcwoIgCI1Rmlx6DeuA2wdjQQOfjc8gD3PWxHVDB0VEroHdL4yh7yInE7fKF9cLTKhIbPB6BLUMMyM3FIJPYJBtPFiErKUx9jPMr9FPgIuKrVgL5FiUNg4gQYqTPtrx6DSuGIpfIdxc7u0af6keI+QC8Dp6GfklDTE3ZT/ykXYCY+2Hs9YLUxW/eW07DIRzhjPpcpEE5j/hM55QzV/acs5GdhPi5JNd46W8OK+CpxsGcbOS8feBzPxE2j2rEb4=
