language: node_js
node_js: stable
dist: trusty
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
script:
  - yarn run lint
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then yarn run test:sauce; fi
  - yarn run test
after_success:
  - yarn run report-coverage
  - yarn run semantic-release
notifications:
  email: change
